apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workiva-zero-row-hider
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: workiva-zero-row-hider
spec:
  source:
    type: Git
    git:
      uri: https://github.com/YOUR_GITHUB_USER/YOUR_REPOSITORY.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: workiva-zero-row-hider:latest
  triggers:
    - type: ConfigChange
